const countryDict = {
    "392": { zh: "日本", en: "Japan", flag: "🇯🇵" },
    "410": { zh: "韓國", en: "South Korea", flag: "🇰🇷" },
    "158": { zh: "台灣", en: "Taiwan", flag: "🇹🇼" },
    "840": { zh: "美國", en: "United States", flag: "🇺🇸" },
    "826": { zh: "英國", en: "United Kingdom", flag: "🇬🇧" },
    "036": { zh: "澳洲", en: "Australia", flag: "🇦🇺" },
    "250": { zh: "法國", en: "France", flag: "🇫🇷" },
    "276": { zh: "德國", en: "Germany", flag: "🇩🇪" },
    "380": { zh: "義大利", en: "Italy", flag: "🇮🇹" },
    "724": { zh: "西班牙", en: "Spain", flag: "🇪🇸" },
    "124": { zh: "加拿大", en: "Canada", flag: "🇨🇦" },
    "076": { zh: "巴西", en: "Brazil", flag: "🇧🇷" },
    "702": { zh: "新加坡", en: "Singapore", flag: "🇸🇬" },
    "764": { zh: "泰國", en: "Thailand", flag: "🇹🇭" },
    "704": { zh: "越南", en: "Vietnam", flag: "🇻🇳" },
    "360": { zh: "印尼", en: "Indonesia", flag: "🇮🇩" },
    "156": { zh: "中國", en: "China", flag: "🇨🇳" },
    "356": { zh: "印度", en: "India", flag: "🇮🇳" },
    "608": { zh: "菲律賓", en: "Philippines", flag: "🇵🇭" },
    "458": { zh: "馬來西亞", en: "Malaysia", flag: "🇲🇾" },
    "484": { zh: "墨西哥", en: "Mexico", flag: "🇲🇽" },
    "032": { zh: "阿根廷", en: "Argentina", flag: "🇦🇷" },
    "710": { zh: "南非", en: "South Africa", flag: "🇿🇦" }
};