const countryDict = {
    "004": { flag: "🇦🇫", en: "Afghanistan", zh: "阿富汗" },
    "248": { flag: "🇦🇽", en: "Åland Islands", zh: "奧蘭群島" },
    "008": { flag: "🇦🇱", en: "Albania", zh: "阿爾巴尼亞" },
    "012": { flag: "🇩🇿", en: "Algeria", zh: "阿爾及利亞" },
    "016": { flag: "🇦🇸", en: "American Samoa", zh: "美屬薩摩亞" },
    "020": { flag: "🇦🇩", en: "Andorra", zh: "安道爾" },
    "024": { flag: "🇦🇴", en: "Angola", zh: "安哥拉" },
    "660": { flag: "🇦🇮", en: "Anguilla", zh: "安吉拉" },
    "010": { flag: "🇦🇶", en: "Antarctica", zh: "南極洲" },
    "028": { flag: "🇦🇬", en: "Antigua and Barbuda", zh: "安地卡及巴布達" },
    "032": { flag: "🇦🇷", en: "Argentina", zh: "阿根廷" },
    "051": { flag: "🇦🇲", en: "Armenia", zh: "亞美尼亞" },
    "533": { flag: "🇦🇼", en: "Aruba", zh: "阿魯巴" },
    "036": { flag: "🇦🇺", en: "Australia", zh: "澳洲" },
    "040": { flag: "🇦🇹", en: "Austria", zh: "奧地利" },
    "031": { flag: "🇦🇿", en: "Azerbaijan", zh: "亞塞拜然" },
    "044": { flag: "🇧🇸", en: "Bahamas", zh: "巴哈馬" },
    "048": { flag: "🇧🇭", en: "Bahrain", zh: "巴林" },
    "050": { flag: "🇧🇩", en: "Bangladesh", zh: "孟加拉" },
    "052": { flag: "🇧🇧", en: "Barbados", zh: "巴貝多" },
    "112": { flag: "🇧🇾", en: "Belarus", zh: "白俄羅斯" },
    "056": { flag: "🇧🇪", en: "Belgium", zh: "比利時" },
    "084": { flag: "🇧🇿", en: "Belize", zh: "貝里斯" },
    "204": { flag: "🇧🇯", en: "Benin", zh: "貝南" },
    "060": { flag: "🇧🇲", en: "Bermuda", zh: "百慕達" },
    "064": { flag: "🇧🇹", en: "Bhutan", zh: "不丹" },
    "068": { flag: "🇧🇴", en: "Bolivia (Plurinational State of)", zh: "玻利維亞" },
    "535": { flag: "🇧🇶", en: "Bonaire, Sint Eustatius and Saba", zh: "荷蘭加勒比區" },
    "070": { flag: "🇧🇦", en: "Bosnia and Herzegovina", zh: "波赫" },
    "072": { flag: "🇧🇼", en: "Botswana", zh: "波札那" },
    "074": { flag: "🇧🇻", en: "Bouvet Island", zh: "布韋島" },
    "076": { flag: "🇧🇷", en: "Brazil", zh: "巴西" },
    "086": { flag: "🇮🇴", en: "British Indian Ocean Territory", zh: "英屬印度洋領地" },
    "096": { flag: "🇧🇳", en: "Brunei Darussalam", zh: "汶萊" },
    "100": { flag: "🇧🇬", en: "Bulgaria", zh: "保加利亞" },
    "854": { flag: "🇧🇫", en: "Burkina Faso", zh: "布吉納法索" },
    "108": { flag: "🇧🇮", en: "Burundi", zh: "蒲隆地" },
    "132": { flag: "🇨🇻", en: "Cabo Verde", zh: "維德角" },
    "116": { flag: "🇰🇭", en: "Cambodia", zh: "柬埔寨" },
    "120": { flag: "🇨🇲", en: "Cameroon", zh: "喀麥隆" },
    "124": { flag: "🇨🇦", en: "Canada", zh: "加拿大" },
    "136": { flag: "🇰🇾", en: "Cayman Islands", zh: "開曼群島" },
    "140": { flag: "🇨🇫", en: "Central African Republic", zh: "中非" },
    "148": { flag: "🇹🇩", en: "Chad", zh: "查德" },
    "152": { flag: "🇨🇱", en: "Chile", zh: "智利" },
    "156": { flag: "🇨🇳", en: "China", zh: "中國" },
    "162": { flag: "🇨🇽", en: "Christmas Island", zh: "聖誕島" },
    "166": { flag: "🇨🇨", en: "Cocos (Keeling) Islands", zh: "科科斯（基林）群島" },
    "170": { flag: "🇨🇴", en: "Colombia", zh: "哥倫比亞" },
    "174": { flag: "🇰🇲", en: "Comoros", zh: "葛摩" },
    "178": { flag: "🇨🇬", en: "Congo", zh: "剛果共和國" },
    "180": { flag: "🇨🇩", en: "Congo (Democratic Republic of the)", zh: "剛果民主共和國" },
    "184": { flag: "🇨🇰", en: "Cook Islands", zh: "庫克群島" },
    "188": { flag: "🇨🇷", en: "Costa Rica", zh: "哥斯大黎加" },
    "384": { flag: "🇨🇮", en: "Côte d'Ivoire", zh: "象牙海岸" },
    "191": { flag: "🇭🇷", en: "Croatia", zh: "克羅埃西亞" },
    "192": { flag: "🇨🇺", en: "Cuba", zh: "古巴" },
    "531": { flag: "🇨🇼", en: "Curaçao", zh: "古拉索" },
    "196": { flag: "🇨🇾", en: "Cyprus", zh: "賽普勒斯" },
    "203": { flag: "🇨🇿", en: "Czechia", zh: "捷克" },
    "208": { flag: "🇩🇰", en: "Denmark", zh: "丹麥" },
    "262": { flag: "🇩🇯", en: "Djibouti", zh: "吉布地" },
    "212": { flag: "🇩🇲", en: "Dominica", zh: "多米尼克" },
    "214": { flag: "🇩🇴", en: "Dominican Republic", zh: "多明尼加" },
    "218": { flag: "🇪🇨", en: "Ecuador", zh: "厄瓜多" },
    "818": { flag: "🇪🇬", en: "Egypt", zh: "埃及" },
    "222": { flag: "🇸🇻", en: "El Salvador", zh: "薩爾瓦多" },
    "226": { flag: "🇬🇶", en: "Equatorial Guinea", zh: "赤道幾內亞" },
    "232": { flag: "🇪🇷", en: "Eritrea", zh: "厄利垂亞" },
    "233": { flag: "🇪🇪", en: "Estonia", zh: "愛沙尼亞" },
    "748": { flag: "🇸🇿", en: "Eswatini", zh: "史瓦帝尼" },
    "231": { flag: "🇪🇹", en: "Ethiopia", zh: "衣索比亞" },
    "238": { flag: "🇫🇰", en: "Falkland Islands (Malvinas)", zh: "福克蘭群島" },
    "234": { flag: "🇫🇴", en: "Faroe Islands", zh: "法羅群島" },
    "242": { flag: "🇫🇯", en: "Fiji", zh: "斐濟" },
    "246": { flag: "🇫🇮", en: "Finland", zh: "芬蘭" },
    "250": { flag: "🇫🇷", en: "France", zh: "法國" },
    "254": { flag: "🇬🇫", en: "French Guiana", zh: "法屬圭亞那" },
    "258": { flag: "🇵🇫", en: "French Polynesia", zh: "法屬玻里尼西亞" },
    "260": { flag: "🇹🇫", en: "French Southern Territories", zh: "法屬南部和南極領地" },
    "266": { flag: "🇬🇦", en: "Gabon", zh: "加彭" },
    "270": { flag: "🇬🇲", en: "Gambia", zh: "甘比亞" },
    "268": { flag: "🇬🇪", en: "Georgia", zh: "喬治亞" },
    "276": { flag: "🇩🇪", en: "Germany", zh: "德國" },
    "288": { flag: "🇬🇭", en: "Ghana", zh: "迦納" },
    "292": { flag: "🇬🇮", en: "Gibraltar", zh: "直布羅陀" },
    "300": { flag: "🇬🇷", en: "Greece", zh: "希臘" },
    "304": { flag: "🇬🇱", en: "Greenland", zh: "格陵蘭" },
    "308": { flag: "🇬🇩", en: "Grenada", zh: "格瑞那達" },
    "312": { flag: "🇬🇵", en: "Guadeloupe", zh: "瓜地洛普" },
    "316": { flag: "🇬🇺", en: "Guam", zh: "關島" },
    "320": { flag: "🇬🇹", en: "Guatemala", zh: "瓜地馬拉" },
    "831": { flag: "🇬🇬", en: "Guernsey", zh: "根西" },
    "324": { flag: "🇬🇳", en: "Guinea", zh: "幾內亞" },
    "624": { flag: "🇬🇼", en: "Guinea-Bissau", zh: "幾內亞比索" },
    "328": { flag: "🇬🇾", en: "Guyana", zh: "蓋亞那" },
    "332": { flag: "🇭🇹", en: "Haiti", zh: "海地" },
    "334": { flag: "🇭🇲", en: "Heard Island and McDonald Islands", zh: "赫德及麥當勞群島" },
    "336": { flag: "🇻🇦", en: "Holy See", zh: "梵蒂岡" },
    "340": { flag: "🇭🇳", en: "Honduras", zh: "宏都拉斯" },
    "344": { flag: "🇭🇰", en: "Hong Kong", zh: "香港" },
    "348": { flag: "🇭🇺", en: "Hungary", zh: "匈牙利" },
    "352": { flag: "🇮🇸", en: "Iceland", zh: "冰島" },
    "356": { flag: "🇮🇳", en: "India", zh: "印度" },
    "360": { flag: "🇮🇩", en: "Indonesia", zh: "印度尼西亞" },
    "364": { flag: "🇮🇷", en: "Iran (Islamic Republic of)", zh: "伊朗" },
    "368": { flag: "🇮🇶", en: "Iraq", zh: "伊拉克" },
    "372": { flag: "🇮🇪", en: "Ireland", zh: "愛爾蘭" },
    "833": { flag: "🇮🇲", en: "Isle of Man", zh: "曼島" },
    "376": { flag: "🇮🇱", en: "Israel", zh: "以色列" },
    "380": { flag: "🇮🇹", en: "Italy", zh: "義大利" },
    "388": { flag: "🇯🇲", en: "Jamaica", zh: "牙買加" },
    "392": { flag: "🇯🇵", en: "Japan", zh: "日本" },
    "832": { flag: "🇯🇪", en: "Jersey", zh: "澤西" },
    "400": { flag: "🇯🇴", en: "Jordan", zh: "約旦" },
    "398": { flag: "🇰🇿", en: "Kazakhstan", zh: "哈薩克" },
    "404": { flag: "🇰🇪", en: "Kenya", zh: "肯亞" },
    "296": { flag: "🇰🇮", en: "Kiribati", zh: "吉里巴斯" },
    "408": { flag: "🇰🇵", en: "Korea (Democratic People's Republic of)", zh: "北韓" },
    "410": { flag: "🇰🇷", en: "South Korea", zh: "南韓" },
    "414": { flag: "🇰🇼", en: "Kuwait", zh: "科威特" },
    "417": { flag: "🇰🇬", en: "Kyrgyzstan", zh: "吉爾吉斯" },
    "418": { flag: "🇱🇦", en: "Lao People's Democratic Republic", zh: "寮國" },
    "428": { flag: "🇱🇻", en: "Latvia", zh: "拉脫維亞" },
    "422": { flag: "🇱🇧", en: "Lebanon", zh: "黎巴嫩" },
    "426": { flag: "🇱🇸", en: "Lesotho", zh: "賴索托" },
    "430": { flag: "🇱🇷", en: "Liberia", zh: "賴比瑞亞" },
    "434": { flag: "🇱🇾", en: "Libya", zh: "利比亞" },
    "438": { flag: "🇱🇮", en: "Liechtenstein", zh: "列支敦斯登" },
    "440": { flag: "🇱🇹", en: "Lithuania", zh: "立陶宛" },
    "442": { flag: "🇱🇺", en: "Luxembourg", zh: "盧森堡" },
    "446": { flag: "🇲🇴", en: "Macao", zh: "澳門" },
    "450": { flag: "🇲🇬", en: "Madagascar", zh: "馬達加斯加" },
    "454": { flag: "🇲🇼", en: "Malawi", zh: "馬拉威" },
    "458": { flag: "🇲🇾", en: "Malaysia", zh: "馬來西亞" },
    "462": { flag: "🇲🇻", en: "Maldives", zh: "馬爾地夫" },
    "466": { flag: "🇲🇱", en: "Mali", zh: "馬利" },
    "466": { flag: "🇲🇹", en: "Malta", zh: "馬爾他" },
    "584": { flag: "🇲🇭", en: "Marshall Islands", zh: "馬紹爾群島" },
    "474": { flag: "🇲🇶", en: "Martinique", zh: "馬丁尼克" },
    "478": { flag: "🇲🇷", en: "Mauritania", zh: "茅利塔尼亞" },
    "480": { flag: "🇲🇺", en: "Mauritius", zh: "模里西斯" },
    "175": { flag: "🇾🇹", en: "Mayotte", zh: "馬約特" },
    "484": { flag: "🇲🇽", en: "Mexico", zh: "墨西哥" },
    "583": { flag: "🇫🇲", en: "Micronesia (Federated States of)", zh: "密克羅尼西亞聯邦" },
    "498": { flag: "🇲🇩", en: "Moldova (Republic of)", zh: "摩爾多瓦" },
    "492": { flag: "🇲🇨", en: "Monaco", zh: "摩納哥" },
    "496": { flag: "🇲🇳", en: "Mongolia", zh: "蒙古國" },
    "499": { flag: "🇲🇪", en: "Montenegro", zh: "蒙特內哥羅" },
    "500": { flag: "🇲🇸", en: "Montserrat", zh: "蒙哲臘" },
    "504": { flag: "🇲🇦", en: "Morocco", zh: "摩洛哥" },
    "508": { flag: "🇲🇿", en: "Mozambique", zh: "莫三比克" },
    "104": { flag: "🇲🇲", en: "Myanmar", zh: "緬甸" },
    "516": { flag: "🇳🇦", en: "Namibia", zh: "納米比亞" },
    "520": { flag: "🇳🇷", en: "Nauru", zh: "諾魯" },
    "524": { flag: "🇳🇵", en: "Nepal", zh: "尼泊爾" },
    "528": { flag: "🇳🇱", en: "Netherlands", zh: "荷蘭" },
    "540": { flag: "🇳🇨", en: "New Caledonia", zh: "新喀里多尼亞" },
    "554": { flag: "🇳🇿", en: "New Zealand", zh: "紐西蘭" },
    "558": { flag: "🇳🇮", en: "Nicaragua", zh: "尼加拉瓜" },
    "562": { flag: "🇳🇪", en: "Niger", zh: "尼日" },
    "566": { flag: "🇳🇬", en: "Nigeria", zh: "奈及利亞" },
    "570": { flag: "🇳🇺", en: "Niue", zh: "紐埃" },
    "574": { flag: "🇳🇫", en: "Norfolk Island", zh: "諾福克島" },
    "807": { flag: "🇲🇰", en: "North Macedonia", zh: "北馬其頓" },
    "580": { flag: "🇲🇵", en: "Northern Mariana Islands", zh: "北馬利安納群島" },
    "578": { flag: "🇳🇴", en: "Norway", zh: "挪威" },
    "512": { flag: "🇴🇲", en: "Oman", zh: "阿曼" },
    "586": { flag: "🇵🇰", en: "Pakistan", zh: "巴基斯坦" },
    "585": { flag: "🇵🇼", en: "Palau", zh: "帛琉" },
    "275": { flag: "🇵🇸", en: "Palestine, State of", zh: "巴勒斯坦" },
    "591": { flag: "🇵🇦", en: "Panama", zh: "巴拿馬" },
    "598": { flag: "🇵🇬", en: "Papua New Guinea", zh: "巴布亞紐幾內亞" },
    "600": { flag: "🇵🇾", en: "Paraguay", zh: "巴拉圭" },
    "604": { flag: "🇵🇪", en: "Peru", zh: "秘魯" },
    "608": { flag: "🇵🇭", en: "Philippines", zh: "菲律賓" },
    "612": { flag: "🇵🇳", en: "Pitcairn", zh: "皮特肯群島" },
    "616": { flag: "🇵🇱", en: "Poland", zh: "波蘭" },
    "620": { flag: "🇵🇹", en: "Portugal", zh: "葡萄牙" },
    "630": { flag: "🇵🇷", en: "Puerto Rico", zh: "波多黎各" },
    "634": { flag: "🇶🇦", en: "Qatar", zh: "卡達" },
    "638": { flag: "🇷🇪", en: "Réunion", zh: "留尼旺" },
    "642": { flag: "🇷🇴", en: "Romania", zh: "羅馬尼亞" },
    "643": { flag: "🇷🇺", en: "Russian Federation", zh: "俄羅斯" },
    "646": { flag: "🇷🇼", en: "Rwanda", zh: "盧安達" },
    "652": { flag: "🇧🇱", en: "Saint Barthélemy", zh: "聖巴瑟米" },
    "654": { flag: "🇸🇭", en: "Saint Helena, Ascension and Tristan da Cunha", zh: "聖赫勒拿、亞森欣和崔斯坦達庫尼亞" },
    "659": { flag: "🇰🇳", en: "Saint Kitts and Nevis", zh: "聖克里斯多福及尼維斯" },
    "662": { flag: "🇱🇨", en: "Saint Lucia", zh: "聖露西亞" },
    "663": { flag: "🇲🇫", en: "Saint Martin (French part)", zh: "法屬聖馬丁" },
    "666": { flag: "🇵🇲", en: "Saint Pierre and Miquelon", zh: "聖皮埃與密克隆群島" },
    "670": { flag: "🇻🇨", en: "Saint Vincent and the Grenadines", zh: "聖文森及格瑞那丁" },
    "882": { flag: "🇼🇸", en: "Samoa", zh: "薩摩亞" },
    "674": { flag: "🇸🇲", en: "San Marino", zh: "聖馬利諾" },
    "678": { flag: "🇸🇹", en: "Sao Tome and Principe", zh: "聖多美普林西比" },
    "682": { flag: "🇸🇦", en: "Saudi Arabia", zh: "沙烏地阿拉伯" },
    "686": { flag: "🇸🇳", en: "Senegal", zh: "塞內加爾" },
    "688": { flag: "🇷🇸", en: "Serbia", zh: "塞爾維亞" },
    "690": { flag: "🇸🇨", en: "Seychelles", zh: "塞席爾" },
    "694": { flag: "🇸🇱", en: "Sierra Leone", zh: "獅子山" },
    "702": { flag: "🇸🇬", en: "Singapore", zh: "新加坡" },
    "534": { flag: "🇸🇽", en: "Sint Maarten (Dutch part)", zh: "荷屬聖馬丁" },
    "703": { flag: "🇸🇰", en: "Slovakia", zh: "斯洛伐克" },
    "705": { flag: "🇸🇮", en: "Slovenia", zh: "斯洛維尼亞" },
    "090": { flag: "🇸🇧", en: "Solomon Islands", zh: "索羅門群島" },
    "090": { flag: "🇸🇴", en: "Somalia", zh: "索馬利亞" },
    "710": { flag: "🇿🇦", en: "South Africa", zh: "南非" },
    "239": { flag: "🇬🇸", en: "South Georgia and the South Sandwich Islands", zh: "南喬治亞和南桑威奇群島" },
    "728": { flag: "🇸🇸", en: "South Sudan", zh: "南蘇丹" },
    "724": { flag: "🇪🇸", en: "Spain", zh: "西班牙" },
    "144": { flag: "🇱🇰", en: "Sri Lanka", zh: "斯里蘭卡" },
    "729": { flag: "🇸🇩", en: "Sudan", zh: "蘇丹" },
    "740": { flag: "🇸🇷", en: "Suriname", zh: "蘇利南" },
    "744": { flag: "🇸🇯", en: "Svalbard and Jan Mayen", zh: "斯瓦爾巴和揚馬延" },
    "752": { flag: "🇸🇪", en: "Sweden", zh: "瑞典" },
    "756": { flag: "🇨🇭", en: "Switzerland", zh: "瑞士" },
    "760": { flag: "🇸🇾", en: "Syrian Arab Republic", zh: "敘利亞" },
    "158": { flag: "🇹🇼", en: "Taiwan", zh: "台灣" },
    "762": { flag: "🇹🇯", en: "Tajikistan", zh: "塔吉克" },
    "834": { flag: "🇹🇿", en: "Tanzania, United Republic of", zh: "坦尚尼亞" },
    "764": { flag: "🇹🇭", en: "Thailand", zh: "泰國" },
    "626": { flag: "🇹🇱", en: "Timor-Leste", zh: "東帝汶" },
    "768": { flag: "🇹🇬", en: "Togo", zh: "多哥" },
    "772": { flag: "🇹🇰", en: "Tokelau", zh: "托克勞" },
    "776": { flag: "🇹🇴", en: "Tonga", zh: "東加" },
    "780": { flag: "🇹🇹", en: "Trinidad and Tobago", zh: "千里達及托巴哥" },
    "788": { flag: "🇹🇳", en: "Tunisia", zh: "突尼西亞" },
    "792": { flag: "🇹🇷", en: "Türkiye", zh: "土耳其" },
    "795": { flag: "🇹🇲", en: "Turkmenistan", zh: "土庫曼" },
    "796": { flag: "🇹🇨", en: "Turks and Caicos Islands", zh: "特克斯與凱科斯群島" },
    "798": { flag: "🇹🇻", en: "Tuvalu", zh: "吐瓦魯" },
    "800": { flag: "🇺🇬", en: "Uganda", zh: "烏干達" },
    "804": { flag: "🇺🇦", en: "Ukraine", zh: "烏克蘭" },
    "784": { flag: "🇦🇪", en: "United Arab Emirates", zh: "阿拉伯聯合大公國" },
    "826": { flag: "🇬🇧", en: "United Kingdom", zh: "英國" },
    "840": { flag: "🇺🇸", en: "United States of America", zh: "美國" },
    "581": { flag: "🇺🇲", en: "United States Minor Outlying Islands", zh: "美國本土外小島嶼" },
    "858": { flag: "🇺🇾", en: "Uruguay", zh: "烏拉圭" },
    "860": { flag: "🇺🇿", en: "Uzbekistan", zh: "烏茲別克" },
    "548": { flag: "🇻🇺", en: "Vanuatu", zh: "萬那杜" },
    "862": { flag: "🇻🇪", en: "Venezuela", zh: "委內瑞拉" },
    "704": { flag: "🇻🇳", en: "Vietnam", zh: "越南" },
    "092": { flag: "🇻🇬", en: "Virgin Islands (British)", zh: "英屬維京群島" },
    "850": { flag: "🇻🇮", en: "Virgin Islands (U.S.)", zh: "美屬維京群島" },
    "876": { flag: "🇼🇫", en: "Wallis and Futuna", zh: "瓦利斯和富圖那" },
    "732": { flag: "🇪🇭", en: "Western Sahara", zh: "西撒哈拉" },
    "887": { flag: "🇾🇪", en: "Yemen", zh: "葉門" },  
    "894": { flag: "🇿🇲", en: "Zambia", zh: "尚比亞" },  
    "716": { flag: "🇿🇼", en: "Zimbabwe", zh: "辛巴威" },  
};
